"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Ella Steinborn and Scout Key, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: eet737 
UT EID 2: smk3946
"""


# TODO: Modify this function. You may delete this comment when you are done.
def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    return group_sum(start + 1, nums, target) or group_sum(start + 1, nums, target - nums[start])

# TODO: Modify this function. You may delete this comment when you are done.
def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if nums[start] == 6:
        return group_sum_6(start + 1, nums, target - nums[start])
    return group_sum_6(start + 1, nums, target) or group_sum_6(start + 1, nums, target - nums[start])
        

# TODO: Modify this function. You may delete this comment when you are done.
def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if nums[start] + 1:
        return group_no_adj(start + 2, nums, target) or group_no_adj(start + 2, nums, target - nums[start])
    else:
        return group_no_adj(start + 1, nums, target) or group_no_adj(start + 1, nums, target - nums[start])


# TODO: Modify this function. You may delete this comment when you are done.
def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 if 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if nums[start] % 5 == 0:
        return group_sum_5(start + 1, nums, target - nums[start])
    else:
        return group_sum_5(start + 1, nums, target) or group_sum_5(start + 1, nums, target - nums[start])


# TODO: Modify this function. You may delete this comment when you are done.
def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if nums[start] == nums[start] + 1:
        return group_sum_clump(start + 1, nums, target - nums[start])
    else:
        return group_sum_clump(start + 1, nums, target) or group_sum_clump(start + 1, nums, target - nums[start])

# TODO: Modify this function
def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    n = len(nums)
    res = []
    sol = []
    array_helper(0, n, sol, res, nums)
    new_lst = []
     
    if nums == []:
        return True
    for index1, value1 in enumerate(res):
        sum = 0
        for index2, value2 in enumerate(value1):
            sum += value2
        if sum in new_lst:
            return True
        new_lst.append(sum)
    return False
  
def array_helper(i, n, sol, res, nums):
    """
    help me
    """
    if i == n:
        res.append(list(sol))
        return res
    array_helper(i+1, n, sol, res, nums)
    sol.append(nums[i])
    array_helper(i+1, n, sol, res, nums)
    sol.pop()

# TODO: Modify this function. You may delete this comment when you are done.
def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    n = len(nums)
    res = []
    sol = []
    array_helper(0, n, sol, res, nums)
    odd_lst = []
    ten_lst = []
    nums_set = set(nums)

    if nums == []:
        return False
    for index1, value1 in enumerate(res):
        sum = 0
        for index2, value2 in enumerate(value1):
            sum += value2
        if sum % 2 == 1:
            for elem in value1:
             odd_lst.append(elem)
        elif sum % 10 == 0:
             for elem in value1:
                ten_lst.append(elem)
    
    both_lst = odd_lst + ten_lst
    set_other = set(both_lst)
    if nums_set == set_other:
        return True
    return False


# TODO: Modify this function. You may delete this comment when you are done.
def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    n = len(nums)
    res = []
    sol = []
    array_helper(0, n, sol, res, nums)
    three_lst = []
    five_lst = []
    nums_set = set(nums)
    if nums == []:
        return True
    for index1, value1 in enumerate(res):
        sum = 0
        for index2, value2 in enumerate(value1):
            sum += value2
        if sum % 3 == 0 and sum % 5 != 0:
            for elem in value1:
             three_lst.append(elem)
        elif sum % 5 == 0:
             for elem in value1:
                five_lst.append(elem) 
    both_lst = three_lst + five_lst
    set_other = set(both_lst)
    if nums_set == set_other:
        return True
    return False

